name: receipt_scanner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  provider: ^6.0.0
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.1.2
  camera: ^0.10.0
  http: ^0.13.3
  url_launcher: ^6.3.0
  fluttertoast: ^8.0.8
  flutter_svg: ^2.0.7
  chips_choice: ^2.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/home-03-stroke-standard.svg
    - assets/icons/camera-01-stroke-standard.svg
    - assets/icons/license-stroke-standard.svg
    - assets/icons/user-circle-stroke-standard.svg
    - assets/icons/menu-02-solid-standard.svg
    - assets/icons/notification-02-stroke-standard.svg